### ISSUE TITLE
How to Delete a node ?

### ISSUE THREAD

**Issue by i-iktear** [jerosoler/drawflow-vue3-example#3]

**Comment by jerosoler** [comment]
The same as without vue.

With the keyboard with the "delete" key or with the second mouse button.

Or using the "removeNodeId(id)" method.

example:
```javascript
editor.removeNodeId('node-1');
```

**Comment by i-iktear** [comment]
but i am not getting how to visible the cross icon in node like connections. With the keyboard with the "delete" working but key or with the second mouse button not working.

**Comment by jerosoler** [comment]
If you have copied this example. you should remove these lines:

https://github.com/jerosoler/drawflow-vue3-example/blob/dbd08ca8156a4aae7a8c5d4f9fe5f29a0f5b0a58/src/assets/style.css#L45

**Comment by i-iktear** [comment]
Thanks a lot. working
