### ISSUE TITLE
is there any way to export editor data from any of node1/2/3 vue files?

### ISSUE THREAD

**Issue by i-iktear** [jerosoler/drawflow-vue3-example#4]

**Comment by jerosoler** [comment]
With value df  in node component:

https://github.com/jerosoler/drawflow-vue3-example/blob/dbd08ca8156a4aae7a8c5d4f9fe5f29a0f5b0a58/src/components/nodes/node1.vue#L46

```javascript
df.export();
```

**Comment by i-iktear** [comment]
Thanks. it's working
